# Generated by Django 4.0.5 on 2022-06-21 11:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
                ('desc', models.TextField(max_length=500)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2022, 6, 21, 20, 44, 53, 871005))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2022, 6, 28, 20, 44, 53, 871005))),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
